apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces/namespace.yaml
- configmaps/configmaps.yaml
- storage/persistent-volumes.yaml
- deployments/postgres-statefulset.yaml
- deployments/redis-deployment.yaml
- deployments/django-deployment.yaml
- deployments/celery-logo-worker.yaml
- deployments/celery-visual-worker.yaml
- deployments/nginx-deployment.yaml
- services/services.yaml
- ingress/ingress.yaml