# Optional webcam support - use with: docker compose -f docker-compose.yml -f docker-compose.webcam.yml up

services:
  backend:
    devices:
      - /dev/video0:/dev/video0  # Linux webcam access
    group_add:
      - video  # Add container user to video group for camera access
    user: "${UID:-1000}:${GID:-1000}"  # Match host user permissions
    # For other platforms, modify as needed:
    # macOS: No device mapping needed, uses AVFoundation
    # Windows: No device mapping needed, uses DirectShow