# Generated by Django 5.0.6 on 2025-08-22 00:19

import ai_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0003_rename_stream_id_to_stream_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='processingqueue',
            name='ai_processi_stream__60b035_idx',
        ),
        migrations.RemoveIndex(
            model_name='videoanalysis',
            name='ai_processi_stream__b961da_idx',
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='confidence_threshold',
            field=models.FloatField(default=ai_processing.models.get_default_confidence_threshold),
        ),
        migrations.AddIndex(
            model_name='processingqueue',
            index=models.Index(fields=['stream_key'], name='ai_processi_stream__aecb17_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysis',
            index=models.Index(fields=['stream_key', 'timestamp'], name='ai_processi_stream__d99710_idx'),
        ),
    ]
