# Generated by Django 5.0.6 on 2025-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0004_remove_processingqueue_ai_processi_stream__60b035_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
