# Generated by Django 5.0.6 on 2025-08-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videostream',
            name='hls_playlist_url',
        ),
    ]
