apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp
  labels:
    app: nginx-rtmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
      - name: nginx-rtmp
        image: tiangolo/nginx-rtmp
        ports:
        - containerPort: 1935
          name: rtmp
        - containerPort: 80
          name: http